### ISSUE TITLE
Wrap up tasks

### ISSUE THREAD

**Issue by ruaridhg** [UCL/Blender_Randomiser#86]
- [x] Test_per_frame_materials (see #42 )
- [x] Test_per_frame_geometry (see #42 )
- [x] Fix geometry testing
- [x] Remove randomise all button or get it working (not for UD panel)
- [x] User defined panel with operators.py rand per frame
- [x] User defined panels with input/output functionality #16  and #17 
- [x] Refactor code i.e. move frequently used functions into utils and #67
- [x] Create issue for colour randomisation input_bounds.json and install_and_enable_addons.py (see #82 )
- [x] Create issue for materials colour export (see #83 )
- [x] Remove print statements in code
- [x] Remove unnecessary files for public release
- [x] Documentation #71
- [x] Add screenshots to docs 
- [x] Make repo public
